import React, { useContext } from 'react';
import MUIDataTable from 'mui-datatables';
import IconButton from '@material-ui/core/IconButton';
import DetailsIcon from '@material-ui/icons/Details';
import DeleteIcon from '@material-ui/icons/Delete';
import {
  Button, Dialog, DialogActions, DialogContent, DialogTitle, Grid, TextField
} from '@material-ui/core';
import { makeStyles } from '@material-ui/core/styles';
import { connect } from 'react-redux';
import CustomToolbar from '../../../../components/CustomToolbar/CustomToolbar';
import PurchaseOrderAcceptanceService from '../../../Services/PurchaseOrderAcceptanceService';
import { ThemeContext } from '../../../App/ThemeWrapper';

const useStyles = makeStyles();

class PurchaseOrderBlock extends React.Component {
  constructor(props) {
    super(props);
    const thelogedUser = JSON.parse(this.props.logedUser);
    this.state = {
      purchaseOrderAcceptanceId: '',
      generatedPurchase: '',
      adminAcceptance: '',
      operationalAcceptance: '',
      openPopUp: false,
      datas: [],
      row: [],
      columns: [
        {
          label: 'Generated By',
          name: 'generatedPurchase',
          options: {
            filter: true
          }
        },
        {
          label: 'Administration Acceptance',
          name: 'adminAcceptance',
          options: {
            filter: true
          }
        },
        {
          label: 'Operational Acceptance',
          name: 'operationalAcceptance',
          options: {
            filter: true
          }
        },
        {
          label: 'Actions',
          name: 'Actions',
          options: {
            filter: false,
            sort: false,
            empty: true,
            customBodyRender: (value, tableMeta) => (
              <React.Fragment>
                {thelogedUser.userRoles[0].actionsNames.financialModule_purchaseOrderAcceptance_access ? (
                  <IconButton onClick={() => this.handleDetails(tableMeta)}>
                    <DetailsIcon color="secondary" />
                  </IconButton>
                ) : null}
                {thelogedUser.userRoles[0].actionsNames.financialModule_purchaseOrderAcceptance_delete ? (
                  <IconButton onClick={() => this.handleDelete(tableMeta)}>
                    <DeleteIcon color="primary" />
                  </IconButton>
                ) : null}
              </React.Fragment>
            )
          }
        }
      ]
    };
  }

  componentDidMount() {
    PurchaseOrderAcceptanceService.getPurchaseOrderAcceptance().then(result => {
      this.setState({ datas: result.data });
    });
    const {
      // eslint-disable-next-line react/prop-types
      changeTheme
    } = this.props;
    changeTheme('greyTheme');
  }

    // eslint-disable-next-line react/sort-comp
    handleDetails = (tableMeta) => {
      const index = tableMeta.tableState.page * tableMeta.tableState.rowsPerPage
            + tableMeta.rowIndex;
        // eslint-disable-next-line react/destructuring-assignment,react/no-access-state-in-setstate
      const id = this.state.datas[index].purchaseOrderAcceptanceId;
      PurchaseOrderAcceptanceService.getPurchaseOrderAcceptanceById(id).then(result => {
        this.setState({
          purchaseOrderAcceptanceId: id,
          generatedPurchase: result.data.generatedPurchase,
          adminAcceptance: result.data.adminAcceptance,
          operationalAcceptance: result.data.operationalAcceptance,
          openPopUp: true
        });
      });
    }

    handleDelete = (tableMeta) => {
      const index = tableMeta.tableState.page * tableMeta.tableState.rowsPerPage
            + tableMeta.rowIndex;
      // eslint-disable-next-line react/destructuring-assignment,react/no-access-state-in-setstate
      const id = this.state.datas[index].purchaseOrderAcceptanceId;
      console.log(id);
      PurchaseOrderAcceptanceService.deletePurchaseOrderAcceptance(id).then(result => {
        this.setState({ datas: result.data });
      });
    };

    handleClose = () => {
      this.setState({ openPopUp: false, openWarning: false });
    };

    handleSave = () => {
      const {
        purchaseOrderAcceptanceId, generatedPurchase, adminAcceptance, operationalAcceptance
      } = this.state;
      const PurchaseOrderAcceptance = {
        purchaseOrderAcceptanceId, generatedPurchase, adminAcceptance, operationalAcceptance
      };
      PurchaseOrderAcceptanceService.updatePurchaseOrderAcceptance(PurchaseOrderAcceptance).then(result => {
        this.setState({ datas: result.data, openPopUp: false });
      });
    };

    handleChange = (ev) => {
      this.setState({ [ev.target.name]: ev.target.value });
    };

    render() {
      const {
        columns, openPopUp, datas, generatedPurchase, adminAcceptance, operationalAcceptance
      } = this.state;
      const {
        logedUser
      } = this.props;
      const thelogedUser = JSON.parse(logedUser);
      let exportButton = false;
      if (thelogedUser.userRoles[0].actionsNames.financialModule_purchaseOrderAcceptance_export) {
        exportButton = true;
      }
      const options = {
        filter: true,
        selectableRows: false,
        filterType: 'dropdown',
        responsive: 'stacked',
        download: exportButton,
        downloadOptions: { filename: 'Purchase order acceptance.csv' },
        print: exportButton,
        rowsPerPage: 10,
        customToolbar: () => (
          <CustomToolbar
            csvData={datas}
            url="/app/gestion-financial/Add Purchase-Acceptance"
            tooltip="add New Purchase Order"
            fileName="Purchase order acceptance"
            hasAddRole={thelogedUser.userRoles[0].actionsNames.financialModule_purchaseOrderAcceptance_create}
            hasExportRole={thelogedUser.userRoles[0].actionsNames.financialModule_purchaseOrderAcceptance_export}
          />
        )
      };

      return (
        <div>
          <MUIDataTable
            title="The Purchase Order Acceptance List"
            data={datas}
            columns={columns}
            options={options}
          />
          <Dialog
            open={openPopUp}
            keepMounted
            scroll="paper"
            onClose={this.handleClose}
            aria-labelledby="alert-dialog-slide-title"
            aria-describedby="alert-dialog-slide-description"
            fullWidth="md"
            maxWidth="md"
          >
            <DialogTitle id="alert-dialog-slide-title"> View Details</DialogTitle>
            <DialogContent dividers>
              <div>
                <Grid
                  container
                  spacing={2}
                  alignItems="flex-start"
                  direction="row"
                  justify="center"
                >
                  <Grid item xs={12} md={6}>
                    <TextField
                      id="generatedPurchase"
                      label="Purchase Order Generated By"
                      variant="outlined"
                      name="generatedPurchase"
                      value={generatedPurchase}
                      required
                      fullWidth
                      onChange={this.handleChange}
                    />
                    <br />
                    <br />
                    <TextField
                      id="adminAcceptance"
                      label="Administration Acceptance By"
                      variant="outlined"
                      name="adminAcceptance"
                      value={adminAcceptance}
                      fullWidth
                      onChange={this.handleChange}
                    />
                    <br />
                    <br />
                    <TextField
                      id="operationalAcceptance"
                      label="Operational Acceptance By"
                      variant="outlined"
                      name="operationalAcceptance"
                      value={operationalAcceptance}
                      fullWidth
                      onChange={this.handleChange}
                    />
                  </Grid>
                </Grid>
              </div>
            </DialogContent>
            <DialogActions>
              <Button color="secondary" onClick={this.handleClose}>
                            Cancel
              </Button>
              {thelogedUser.userRoles[0].actionsNames.financialModule_purchaseOrderAcceptance_modify ? (
                <Button
                  variant="contained"
                  color="primary"
                  onClick={this.handleSave}
                >
                            save
                </Button>
              ) : null}
            </DialogActions>
          </Dialog>
        </div>
      );
    }
}
const mapStateToProps = () => ({
  logedUser: localStorage.getItem('logedUser')
});
const PurchaseOrderMapped = connect(
  mapStateToProps,
  null
)(PurchaseOrderBlock);

export default () => {
  const { changeTheme } = useContext(ThemeContext);
  const classes = useStyles();
  return <PurchaseOrderMapped changeTheme={changeTheme} classes={classes} />;
};
